apiVersion: apps/v1
kind: Deployment
metadata:
  name:  event-bus-depl
spec:
  selector:
    matchLabels:
      app: event-bus
  replicas: 1
  template:
    metadata:
      labels:
        app:  event-bus
    spec:
      containers:
      - name:  event-bus
        image:  kimmi1206/event-bus
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
---
# Cluster IP
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  # type: ClusterIP     # There is no need to specify clusterip, it is the default value
  selector:
    app: event-bus
  ports:
  - name: event-bus
    protocol: TCP
    port: 4005
    targetPort: 4005
